// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFyARTe5htvFenm-AwoVUOES3iwce8sjM',
    appId: '1:327324836622:web:252e7906b04fde8136ad5f',
    messagingSenderId: '327324836622',
    projectId: 'eshop-multivendor-new',
    authDomain: 'eshop-multivendor-new.firebaseapp.com',
    storageBucket: 'eshop-multivendor-new.appspot.com',
    measurementId: 'G-J7Y3R8EJPC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA86yj-bZs6o27AqRIjgwXAh1hrXjb2bvs',
    appId: '1:919271127861:android:2d6f9b57cc3974e3312a7c',
    messagingSenderId: '919271127861',
    projectId: 'eshop-18689',
    databaseURL: 'https://eshop-18689-default-rtdb.firebaseio.com',
    storageBucket: 'eshop-18689.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByMO2Zm4VdE8ie_T2Kg12i4Owfyh9ERvc',
    appId: '1:919271127861:ios:e795f7ea10db3c82312a7c',
    messagingSenderId: '919271127861',
    projectId: 'eshop-18689',
    databaseURL: 'https://eshop-18689-default-rtdb.firebaseio.com',
    storageBucket: 'eshop-18689.appspot.com',
    iosClientId: '919271127861-o36ia65agra8msrjnfhsvi5tcp1cn2hi.apps.googleusercontent.com',
    iosBundleId: 'wrteam.eshop.multivendor',
  );

}